name: Release

on:
  push:
    tags:
      - 'v*'  # v1.0.0, v1.2.3 のような形式のタグにのみ反応

jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # リリース作成のために必要
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build
    
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Find JAR file
      id: find_jar
      run: |
        JAR_FILE=$(find build/libs -name "BeeSpeed*.jar" -not -name "*-sources.jar" -not -name "*-javadoc.jar" | head -1)
        echo "JAR_FILE=$JAR_FILE" >> $GITHUB_OUTPUT
        echo "JAR_NAME=$(basename $JAR_FILE)" >> $GITHUB_OUTPUT
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.find_jar.outputs.JAR_FILE }}
        name: Release v${{ steps.get_version.outputs.VERSION }}
        body: |
          BeeSpeed v${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
